### ISSUE TITLE
Costs for typical project deployment

### ISSUE THREAD

**Issue by briancaffey** [netsome/djambda#2]
Hi, awesome project. I have been looking for a good way to do Django in Lambda without using Zappa or Serverless Framework and I really like this approach. I have a question about pricing. For the typical deployment, what are the costs for this project on a daily or monthly basis? Does the default deployment create 3 NAT Gateways? I assume that is the biggest cost, followed by RDS. Thanks

**Comment by jwygoda** [comment]
Thanks for the feedback. The default setup fits into Free Tier. It doesn't create NAT Gateways but you can set it up in `terraform/modules/django/vpc.tf`, it's a bit pricey though. You can read more about NAT Gateway Scenarios [here](https://github.com/terraform-aws-modules/terraform-aws-vpc#nat-gateway-scenarios). [NAT instance](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html) on t2.micro EC2 fits into Free Tier but it's more work to set it up and maintain. If you don't need internet access but want to connect to other AWS services you can always enable [Gateway VPC endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html) or [Interface VPC endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html). Django tf module takes `enable_s3_endpoint`, `enable_dynamodb_endpoint` and `enable_ses_endpoint` variables, check out `terraform/modules/django/variables.tf`
