### ISSUE TITLE
What version of django and python can I use this with?

### ISSUE THREAD

**Issue by simkimsia** [netsome/djambda#6]
Version of django and python I can use this with 

And does it matter that I usually deploy django with django Rest framework?

**Comment by jwygoda** [comment]
I've tested it with python 3.8 (default in `django` terraform module). You can change it by setting a `lambda_runtime` variable in the module.

You can add `djangorestframework` to `requirements/base.in`. Remember to run `make requirements` to pin dependencies versions.
